version: '3.8'

services:
  # PostgreSQL Database (local development)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fdduser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fddpassword}
      POSTGRES_DB: ${POSTGRES_DB:-fdd_pipeline}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-fdduser}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prefect Server
  prefect-server:
    image: prefecthq/prefect:2.14-python3.11
    command: prefect server start --host 0.0.0.0
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://${POSTGRES_USER:-fdduser}:${POSTGRES_PASSWORD:-fddpassword}@postgres:5432/${POSTGRES_DB:-fdd_pipeline}
    ports:
      - "4200:4200"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FDD Pipeline API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER:-fdduser}:${POSTGRES_PASSWORD:-fddpassword}@postgres:5432/${POSTGRES_DB:-fdd_pipeline}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      # Prefect
      PREFECT_API_URL: http://prefect-server:4200/api
      # Google Drive
      GDRIVE_CREDS_JSON: ${GDRIVE_CREDS_JSON}
      GDRIVE_FOLDER_ID: ${GDRIVE_FOLDER_ID}
      # LLM APIs
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
      # MinerU
      MINERU_MODE: ${MINERU_MODE:-local}
      MINERU_DEVICE: ${MINERU_DEVICE:-cpu}
      MINERU_MODEL_PATH: /app/models
      # API
      INTERNAL_API_TOKEN: ${INTERNAL_API_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      prefect-server:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - mineru_models:/app/models
    command: ["python", "-m", "src.api.run", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prefect Agent
  prefect-agent:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Same environment as API
      DATABASE_URL: postgresql://${POSTGRES_USER:-fdduser}:${POSTGRES_PASSWORD:-fddpassword}@postgres:5432/${POSTGRES_DB:-fdd_pipeline}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      PREFECT_API_URL: http://prefect-server:4200/api
      GDRIVE_CREDS_JSON: ${GDRIVE_CREDS_JSON}
      GDRIVE_FOLDER_ID: ${GDRIVE_FOLDER_ID}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
      MINERU_MODE: ${MINERU_MODE:-local}
      MINERU_DEVICE: ${MINERU_DEVICE:-cpu}
      MINERU_MODEL_PATH: /app/models
    command: ["prefect", "agent", "start", "-q", "default"]
    depends_on:
      prefect-server:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - mineru_models:/app/models
    restart: unless-stopped

  # Ollama (Local LLM) - Optional
  ollama:
    image: ollama/ollama:latest
    profiles: ["with-ollama"]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0

  # pgAdmin (Database UI) - Optional
  pgadmin:
    image: dpage/pgadmin4:latest
    profiles: ["dev-tools"]
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@fddpipeline.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  mineru_models:
  ollama_data:
  pgadmin_data: